info:
  name: ${spring.application.name}
  component: Feign Application

app:
  center: http://192.168.0.43:8000/eureka/
  oauth: http://192.168.0.17:8002/account
  security:
    moduleAuthPath: http://account/account
    ignores: /image/**,/css/**,/js/**,/webjars/**
    authorities:
      permitAll: /index2
      hasUrlAuthority('read'): /auth/users,/auth/orgs
      hasModuleAuthority('yhgl:add'): /auth/user/create
      hasAnyAuthority('ROLE_USER'): /resource1/**,/catalog1/**,/index
      hasAnyAuthority('ROLE_ADMIN_2'): /call
      authenticated : true
    resources:
      hasScope('get_resource_info'): /resource/**,/catalog/**

spring:
  rabbitmq:
    host: 10.1.1.141
#    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    port: 6379
    host: 10.1.1.141

server:
  port: ${port:10003}

druid:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    #初始化连接数量，最大最小连接数
    initialSize: 5
    maxActive: 10
    minIdle: 3
    #获取连接等待超时的时间
    maxWait: 600000
    #超过时间限制是否回收
    removeAbandoned: true
    #超过时间限制多长
    removeAbandonedTimeout: 180
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 600000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
filters: stat

mybatis:
  typeAliasesPackage: com.example.web.model
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/config/mybatis-spring.xml

logging:
  level:
    org.springframework: WARN
    cn.gtmap.gtc.plugins: DEBUG
